FORMAT: 1A
HOST: http://onboarding.example.org

# Mt API 1 sketch
This is a preliminary sketch of the Onboarding API
## Home [/]
### Get Home Resource [GET]
+ Response 200 (text/html)
            <h2>Home</h2>